# Generated by Django 4.2 on 2023-04-11 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('A_theBlogNew', '0006_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
