# Generated by Django 4.2 on 2023-04-20 07:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('B_01BaseApp', '0006_alter_inkhawminchhiarnablognew_mat_members'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inkhawminchhiarnablognew',
            name='marka_grp_cmt',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(24)]),
        ),
    ]
