# Generated by Django 4.2 on 2023-04-21 06:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('B_01BaseApp', '0008_alter_inkhawminchhiarnablognew_johan_grp_cmt_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inkhawminchhiarnablognew',
            name='leader_secy',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(2)]),
        ),
    ]
